# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
