# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_artist_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_length',
            field=models.IntegerField(default=''),
        ),
    ]
