# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20171223_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_length',
            new_name='length',
        ),
    ]
