# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20171223_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='playlist.Song'),
        ),
    ]
