# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20171226_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
