# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='friends_list.User'),
        ),
    ]
