# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171218_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_title',
            field=models.TextField(default=''),
        ),
    ]
