# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_books_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_last_name',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
