# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171218_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
