# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='books',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_book_review',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
