# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171228_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_book_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_review', to='users.Users'),
        ),
    ]
