# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171228_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
