# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171228_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='books',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_book_review',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
