# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='book_author',
            field=models.ManyToManyField(related_name='book_authors', to='book_authors.Books'),
        ),
    ]
