# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20171212_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='books',
            new_name='book',
        ),
    ]
