# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_auto_20171212_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='books are cool'),
            preserve_default=False,
        ),
    ]
